const inquirer = require('inquirer')
const fs = require('fs')
const employee = require('./library/employee')
const manager = require("./library/manager")
const enginner = require('./library/engineer')
const intern = require("./library/intern")